dotfiles_repo: https://github.com/markruler/settings.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/Documents/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .vimrc
  - .tmux.conf
